//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Анализ_ежедневной_рыночной_цены_криптовалюты.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Анализ_ежедневной_рыночной_цены_криптовалюты.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to slug,symbol,name,date,ranknow,open,high,low,close,volume,market,close_ratio,spread
        ///bitcoin,BTC,Bitcoin,2013-04-28,1,135.3,135.98,132.1,134.21,0,1488566728,0.5438,3.88
        ///bitcoin,BTC,Bitcoin,2013-04-29,1,134.44,147.49,134,144.54,0,1603768865,0.7813,13.49
        ///bitcoin,BTC,Bitcoin,2013-04-30,1,144,146.93,134.05,139,0,1542813125,0.3843,12.88
        ///bitcoin,BTC,Bitcoin,2013-05-01,1,139,139.89,107.72,116.99,0,1298954594,0.2882,32.17
        ///bitcoin,BTC,Bitcoin,2013-05-02,1,116.38,125.6,92.28,105.21,0,1168517495,0.3881,33.32
        ///bitcoin,BTC [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string crypto_markets {
            get {
                return ResourceManager.GetString("crypto_markets", resourceCulture);
            }
        }
    }
}
